apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: deploy-demo-pipeline
description: Security-focused CI/CD pipeline on GCP
serialPipeline:
 stages:
 - targetId: demo-test
 - targetId: demo-prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-test
description: test cluster
gke:
<<<<<<< HEAD
  cluster: projects/cicd-demo-375021/locations/us-west1-c/clusters/demo-test
=======
  cluster: projects/cloudy-test/locations/us-west1-c/clusters/demo-test
>>>>>>> 5c38ceee1279791dd86d686de5f42328526e374d
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-prod
description: prod cluster
requireApproval: true
gke:
<<<<<<< HEAD
  cluster: projects/cicd-demo-375021/locations/us-west1-c/clusters/demo-prod
=======
  cluster: projects/cloudy-prod/locations/us-west1-c/clusters/demo-prod
>>>>>>> 5c38ceee1279791dd86d686de5f42328526e374d
